name: Vessel
favicon: null
layout_spectrum: 0.7915962100960314
typography_spectrum: 0.6925057815387845
title: vessel - urns and what to do when someone dies
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.08081759884953499
  lightness: 0.20468993880786002
  saturation: 0.42781990533694625
  rhythmicContrast: 0.48266981495544314
purpose: []
