name: Vessel
favicon: null
layout_spectrum: 0.51202
typography_spectrum: 0.76018
title: vessel - urns and exploring the process of death
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1012'
    - '#f9f9f9'
    - '#3d4a30'
    - '#b2554f'
    - '#808e52'
  brandStrength: 0
  lightness: 0.4375
  saturation: 0.3125
  rhythmicContrast: 0.48266981495544314
purpose: []
