name: Vessel
favicon: null
layout_spectrum: 0.26056
typography_spectrum: 0.7277
title: vessel - urns and the process of dying
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8dae9'
    - '#17221e'
    - '#bd5841'
    - '#5d728a'
    - '#f19963'
  brandStrength: 0.875
  lightness: 0.4375
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
